### ISSUE TITLE
Exposing nix expression AST

### ISSUE THREAD

**Issue by costrouc** [Mic92/pythonix#1]
I wanted to open an issue to judge what you think about exposing the nix expression AST in `pythonix`. This package is already great for evaluating expressions and working with the results in python. I would like to add a PR for AST support because this would enable a whole set of tooling to be easily made. For example

 - automate alphabetically sorting packages
 - automate enforcing a code style to expressions
 - could also benefit code editors with handling nix expressions

I have already found that the AST is exposed at https://github.com/NixOS/nix/blob/master/src/libexpr/nixexpr.hh . I will need to have knowledge of interfacing C++ with python for my future job (without using cython) and I think this is a doable project that could provide a lot of benefit.

**Comment by Mic92** [comment]
Sounds good to me! Go ahead.

**Comment by costrouc** [comment]
I will continue the conversation in the new PR when I open it.
