### ISSUE TITLE
nix.so is being built for a wrong python version when it differs from meson

### ISSUE THREAD

**Issue by orivej** [Mic92/pythonix#6]
Currently in Nixpkgs python3 is python38, and `python3Packages.pythonix` is built correctly, but `python37Packages.pythonix` and `python39Packages.pythonix` both install `nix.so` in `lib/python3.8/site-packages`, thus a dependent package `python39Packages.nixpkgs` fails to import `nix`: https://github.com/NixOS/nixpkgs/pull/107623#issuecomment-751396755

I don't know whether the root cause of this issue is in pythonix (in how it uses meson), meson (which seems most likely to me), or Nixpkgs.

**Comment by Mic92** [comment]
Ok. Will look into this.

**Comment by orivej** [comment]
Thanks!

**Comment by Mic92** [comment]
It needs to override python in meson as shown here: https://github.com/Mic92/pythonix/blob/ff5a29a9fd3e74c5b5741e394bfe578b6f2a9a52/default.nix#L17
